function ex = goInit(ex,varargin)
% function ex = goInit(ex,varargin)
%
% goInit evaluates <ex.initFunc>. Do not edit this file.
% Instead, write a initFunc function, and set ex.initFunc to
% the handle to that function

ex = feval(ex.initFunc,ex,varargin{:});
