function ex = goPause(ex,varargin)
% function ex = goPause(ex,varargin)
%
% goPause evaluates <ex.pauseFunc>. Do not edit this file.
% Instead, write a pauseFunc function, and set ex.pauseFunc to
% the handle to that function

ex = feval(ex.pauseFunc,ex,varargin{:});
