function ex = goPresentTrial(ex,varargin)
% function ex = goPresentTrial(ex,varargin)
%
% goPresentTrial evaluates <ex.presentTrialFunc>. Do not edit this file.
% Instead, write a presentTrialFunc function, and set ex.presentTrialFunc to
% the handle to that function

ex = feval(ex.presentTrialFunc,ex,varargin{:});
