function ex = goReportTrial(ex,varargin)
% function ex = goReportTrial(ex,varargin)
%
% goReportTrial evaluates <ex.reportTrialFunc>. Do not edit this file.
% Instead, write a reportTrialFunc function, and set ex.reportTrialFunc to
% the handle to that function

ex = feval(ex.reportTrialFunc,ex,varargin{:});
