function ex = goSaveData(ex,varargin)
% function ex = goSaveData(ex,varargin)
%
% goSaveData evaluates <ex.saveDataFunc>. Do not edit this file.
% Instead, write a saveDataFunc function, and set ex.saveDataFunc to
% the handle to that function

ex = feval(ex.saveDataFunc,ex,varargin{:});
