function ex = goWrapup(ex,varargin)
% function ex = goWrapup(ex,varargin)
%
% goWrapup evaluates <ex.wrapupFunc>. Do not edit this file.
% Instead, write a wrapupFunc function, and set ex.wrapupFunc to
% the handle to that function

ex = feval(ex.wrapupFunc,ex,varargin{:});
