function r = goGetResponse(r,varargin)
%function r = goGetResponse(r,varargin)
%
% goGetResponse evaluates <r.getResponseFunc>. Do not edit this file.
% Instead, write a getResponseFunc function, and set r.getResponseFunc to
% the handle to that function


r = feval(r.getResponseFunc,r,varargin{:});

    