function r = goPresentFeedback(r,varargin)
%function r = goPresentFeedback(r,varargin)
%
% goPresentFeedback evaluates <r.presentFeedbackFunc>. Do not edit this file.
% Instead, write a presentFeedbackFunc function, and set r.presentFeedbackFunc to
% the handle to that function

r = feval(r.presentFeedbackFunc,r,varargin{:});

    