function r = goPrepResponse(r,varargin)
%function r = goPrepResponse(r,varargin)
%
% goPrepResponse evaluates <r.prepResponseFunc>. Do not edit this file.
% Instead, write a prepResponseFunc function, and set r.prepResponseFunc to
% the handle to that function


r = feval(r.prepResponseFunc,r,varargin{:});

    