function r = goTellDone(r,varargin)
%function r = goTellDone(r,varargin)
%
% goTellDone evaluates <r.TellDoneFunc>. Do not edit this file.
% Instead, write a tellDoneFunc function, and set r.tellDoneFunc to
% the handle to that function


r = feval(r.tellDoneFunc,r,varargin{:});

    