function r = goWaitForSubject(r,varargin)
%function r = goWaitForSubject(r,varargin)
%
% goWaitForSubject evaluates <r.waitForSubjectFunc>. Do not edit this file.
% Instead, write a waitForSubjectFunc function, and set r.waitForSubjectFunc to
% the handle to that function


r = feval(r.waitForSubjectFunc,r,varargin{:});

    