function [val, t] = goNextValue(t,varargin)
% function [val, t] = goNextValue(t,varargin)
%
% goNextValue evaluates <r.nextValueFunc>. Do not edit this file.
% Instead, write a nextValueFunc function, and set t.nextValueFunc to
% the handle to that function

[val t] = feval(t.nextValueFunc,t,varargin{:});
