function varargout = goPlot(t,varargin)
% function goPlot(t,varargin)
%
% goPlot evaluates <r.plotFunc>. Do not edit this file.
% Instead, write a plotFunc function, and set t.plotFunc to
% the handle to that function

varargout = {feval(t.plotFunc,t,varargin{:})};
